CREATE TABLE IF NOT EXISTS `sql4401943`.`USER_DATA` (
  `ENTRY_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `DATE_T` VARCHAR(64) NOT NULL,
  `DESC_T` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`ENTRY_ID`));


CREATE TABLE IF NOT EXISTS `sql4401943`.`LOGIN_CREDENTIALS` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(64) NOT NULL,
  `PASSPHRASE` VARCHAR(256) NOT NULL,
  `EMAIL` VARCHAR(64) NOT NULL,
  `API_AUTHKEY` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`USER_ID`));
  

  CREATE TABLE IF NOT EXISTS `sql4401943`.`PERSONAL_INFORMATION` (
  `ENTRY_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `NICKNAME` VARCHAR(64) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `MIDDLE_NAMES` VARCHAR(128) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `AGE` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`ENTRY_ID`));